### PR TITLE
feat: add quickjs and qjsc

### PR DESCRIPTION
**Pull request by gengjiawen**
Fix: https://github.com/napi-bindings/quickjs-build/issues/5

Maybe `src/qjscalc.c` `src/repl.c` better auto generated by qjsc, but I have not found a good way to do this.

@NickNaso PTAL

### CODE REVIEW

**Comment by gengjiawen** [comment]
Windows build failed with, not sure official quickjs use which compiler : 

```console
C:/Program Files/Git/tdm-gcc-9.2.0/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: libqjs.a(quickjs.c.obj):quickjs.c:(.text+0x42c7d): undefined reference to `clock_gettime'
collect2.exe: error: ld returned 1 exit status
CMakeFiles/quickjs.dir/build.make:133: recipe for target 'quickjs.exe' failed
mingw32-make.exe[2]: *** [quickjs.exe] Error 1
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/quickjs.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/quickjs.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
Error: Process completed with exit code 2.
```

**Comment by NickNaso** [comment]
Hi @gengjiawen,
I tested the executable generated by the builfing process, for the *nix system all seems good, but for windows thare are some problems.
If you try to start the executable for Windows you will get this error:
win-error
The library `libwinpthread-1.dll` is placed in `C:\msys64\mingw64\bin` so I copied it on the same folder of the executable files and then they run without any errors. The first idea was to copy this library to the build folder and then put it in the final artifact, but I don't like this solution. I made some searches and I found that it is possible to link statically the necessary libraries. To test this idea I checkout your solution and added the following settings to the `CMakeLists.txt` file:

```
set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-Bstatic,--whole-archive -lwinpthread -Wl,--no-whole-archive")
```
At the end I obtained an executable that does not need any other libraries to start and it seems to work based on my experiments. What do you think? Do you want to update the ``CMakeLists.txt` to handle this on windows systems?

**Comment by gengjiawen** [comment]
> If you try to start the executable for Windows you will get this error

Yeap. I have run into this issue too. But on the generated github action artifacts. this looks no longer needed, the qjsc.exe can directly run. Not sure why.

But I do agree we should get consistent behavior. From what I test, adding -Bstatic should be enough. Can you give this a test ?

**Comment by gengjiawen** [comment]
I pushed again, can you try the new one ?

**Comment by NickNaso** [comment]
> > If you try to start the executable for Windows you will get this error
> 
> Yeap. I have run into this issue too. But on the generated github action artifacts. this looks no longer needed, the qjsc.exe can directly run. Not sure why.
> 
> But I do agree we should get consistent behavior. From what I test, adding -Bstatic should be enough. Can you give this a test ?

The problem is that in the local machine you have set the path for the `mingw` so when you run the executable the system find the `libwinpthread-1.dll` library. 

I tested the nel build and it works so I'm going to approve the PR and waiting your feedback to go forward to merge and publish.

Thank a lot for this work.

**Review by NickNaso — APPROVED** [review]

**Comment by gengjiawen** [comment]
Thanks for this amazing project ❤️

**Comment by gengjiawen** [comment]
Also please draft a new release, I want to add quickjs macOS support for esvu.

**Pull request merged**
